apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: blood-bank-prod
  region: us-east-1
availabilityZones:
  - us-east-1a
  - us-east-1b
nodeGroups:
  - name: ng-1 
    instanceType: t2.medium
    desiredCapacity: 3
    minSize: 3
    maxSize: 5
    privateNetworking: true
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        imageBuilder: true
        awsLoadBalancerController: true
        autoScaler: true

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::898855110204:policy/AWSLoadBalancerControllerIAMPolicy

addons:
- name: aws-ebs-csi-driver
  version: latest
  resolveConflicts: overwrite
- name: aws-efs-csi-driver
  version: latest 
  resolveConflicts: overwrite


