#echo -n "sorav" | base64
#c29yYXY=
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels: 
    app: mysql
    app.kubernetes.io/name: mysql
type: Opaque
data:
  ROOT_PASSWORD: c29yYXY=