apiVersion: v1
kind: Service
metadata:
  name: mysql-headless-svc
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
spec:
  clusterIP: None
  ports:
  - name: mysql
    port: 3306
  selector:
    app: mysql